# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HW2_5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import torchvision


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(605, 467)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 181, 351))
        self.groupBox.setObjectName("groupBox")
        self.ButtonLoadImage = QtWidgets.QPushButton(self.groupBox)
        self.ButtonLoadImage.setGeometry(QtCore.QRect(20, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ButtonLoadImage.setFont(font)
        self.ButtonLoadImage.setObjectName("ButtonLoadImage")
        self.ButtonShowImages = QtWidgets.QPushButton(self.groupBox)
        self.ButtonShowImages.setGeometry(QtCore.QRect(20, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ButtonShowImages.setFont(font)
        self.ButtonShowImages.setObjectName("ButtonShowImages")
        self.ButtonShowDistribution = QtWidgets.QPushButton(self.groupBox)
        self.ButtonShowDistribution.setGeometry(QtCore.QRect(20, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ButtonShowDistribution.setFont(font)
        self.ButtonShowDistribution.setObjectName("ButtonShowDistribution")
        self.ButtonShowComparison = QtWidgets.QPushButton(self.groupBox)
        self.ButtonShowComparison.setGeometry(QtCore.QRect(20, 230, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ButtonShowComparison.setFont(font)
        self.ButtonShowComparison.setObjectName("ButtonShowComparison")
        self.ButtonShowModelStructure = QtWidgets.QPushButton(self.groupBox)
        self.ButtonShowModelStructure.setGeometry(QtCore.QRect(20, 180, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ButtonShowModelStructure.setFont(font)
        self.ButtonShowModelStructure.setObjectName("ButtonShowModelStructure")
        self.ButtonInference = QtWidgets.QPushButton(self.groupBox)
        self.ButtonInference.setGeometry(QtCore.QRect(20, 280, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ButtonInference.setFont(font)
        self.ButtonInference.setObjectName("ButtonInference")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        print(torch.cuda.is_available())
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "5. ResNet50"))
        self.ButtonLoadImage.setText(_translate("Dialog", "Load Image"))
        self.ButtonShowImages.setText(_translate("Dialog", "1. Show Images"))
        self.ButtonShowDistribution.setText(_translate("Dialog", "2. Show Distribution"))
        self.ButtonShowComparison.setText(_translate("Dialog", "4. Show Comparison"))
        self.ButtonShowModelStructure.setText(_translate("Dialog", "3. Show Model Structure"))
        self.ButtonInference.setText(_translate("Dialog", "5. Inference"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
